### ISSUE TITLE
node 9.0.0 - recipe for target failed

### ISSUE THREAD

**Issue by timotejroiko** [paixaop/node-sodium#123]
libsodium compiles fine, but node-sodium outputs the following:

```> sodium@2.0.1 install /home/genesis/astrobot/node_modules/sodium
> node install.js --install

echo Build node-sodium module
Build node-sodium module
node-gyp rebuild
make[1]: Entering directory '/home/genesis/astrobot/node_modules/sodium/build'
  CXX(target) Release/obj.target/sodium/src/crypto_aead.o
In file included from ../../nan/nan.h:192:0,
                 from ../src/include/node_sodium.h:20,
                 from ../src/crypto_aead.cc:8:
../../nan/nan_maybe_43_inl.h: In function ‘Nan::Maybe<bool> Nan::ForceSet(v8::Local<v8::Object>, v8::Local<v8::Value>, v8::Local<v8::Value>, v8::PropertyAttribute)’:
../../nan/nan_maybe_43_inl.h:112:73: warning: ‘v8::Maybe<bool> v8::Object::ForceSet(v8::Local<v8::Context>, v8::Local<v8::Value>, v8::Local<v8::Value>, v8::PropertyAttribute)’ is deprecated: Use CreateDataProperty / DefineOwnProperty [-Wdeprecated-declarations]
   return obj->ForceSet(isolate->GetCurrentContext(), key, value, attribs);
                                                                         ^
In file included from /home/genesis/.node-gyp/9.0.0/include/node/v8.h:26:0,
                 from /home/genesis/.node-gyp/9.0.0/include/node/node.h:63,
                 from ../src/include/node_sodium.h:11,
                 from ../src/crypto_aead.cc:8:
/home/genesis/.node-gyp/9.0.0/include/node/v8.h:3115:29: note: declared here
                 Maybe<bool> ForceSet(Local<Context> context, Local<Value> key,
                             ^
/home/genesis/.node-gyp/9.0.0/include/node/v8config.h:318:3: note: in definition of macro ‘V8_DEPRECATED’
   declarator __attribute__((deprecated(message)))
   ^
../src/crypto_aead.cc: In function ‘Nan::NAN_METHOD_RETURN_TYPE bind_crypto_aead_aes256gcm_encrypt_detached_afternm(Nan::NAN_METHOD_ARGS_TYPE)’:
../src/crypto_aead.cc:326:88: error: no matching function for call to ‘v8::Object::ForceSet(v8::Local<v8::String>, v8::Local<v8::Object>&, v8::PropertyAttribute)’
         result->ForceSet(Nan::New<String>("cipherText").ToLocalChecked(), c, DontDelete);
                                                                                        ^
In file included from /home/genesis/.node-gyp/9.0.0/include/node/v8.h:26:0,
                 from /home/genesis/.node-gyp/9.0.0/include/node/node.h:63,
                 from ../src/include/node_sodium.h:11,
                 from ../src/crypto_aead.cc:8:
/home/genesis/.node-gyp/9.0.0/include/node/v8.h:3115:29: note: candidate: v8::Maybe<bool> v8::Object::ForceSet(v8::Local<v8::Context>, v8::Local<v8::Value>, v8::Local<v8::Value>, v8::PropertyAttribute)
                 Maybe<bool> ForceSet(Local<Context> context, Local<Value> key,
                             ^
/home/genesis/.node-gyp/9.0.0/include/node/v8config.h:318:3: note: in definition of macro ‘V8_DEPRECATED’
   declarator __attribute__((deprecated(message)))
   ^
/home/genesis/.node-gyp/9.0.0/include/node/v8.h:3115:29: note:   no known conversion for argument 3 from ‘v8::PropertyAttribute’ to ‘v8::Local<v8::Value>’
                 Maybe<bool> ForceSet(Local<Context> context, Local<Value> key,
                             ^
/home/genesis/.node-gyp/9.0.0/include/node/v8config.h:318:3: note: in definition of macro ‘V8_DEPRECATED’
   declarator __attribute__((deprecated(message)))
   ^
../src/crypto_aead.cc:327:83: error: no matching function for call to ‘v8::Object::ForceSet(v8::Local<v8::String>, v8::Local<v8::Object>&, v8::PropertyAttribute)’
         result->ForceSet(Nan::New<String>("mac").ToLocalChecked(), mac, DontDelete);
                                                                                   ^
In file included from /home/genesis/.node-gyp/9.0.0/include/node/v8.h:26:0,
                 from /home/genesis/.node-gyp/9.0.0/include/node/node.h:63,
                 from ../src/include/node_sodium.h:11,
                 from ../src/crypto_aead.cc:8:
/home/genesis/.node-gyp/9.0.0/include/node/v8.h:3115:29: note: candidate: v8::Maybe<bool> v8::Object::ForceSet(v8::Local<v8::Context>, v8::Local<v8::Value>, v8::Local<v8::Value>, v8::PropertyAttribute)
                 Maybe<bool> ForceSet(Local<Context> context, Local<Value> key,
                             ^
/home/genesis/.node-gyp/9.0.0/include/node/v8config.h:318:3: note: in definition of macro ‘V8_DEPRECATED’
   declarator __attribute__((deprecated(message)))
   ^
/home/genesis/.node-gyp/9.0.0/include/node/v8.h:3115:29: note:   no known conversion for argument 3 from ‘v8::PropertyAttribute’ to ‘v8::Local<v8::Value>’
                 Maybe<bool> ForceSet(Local<Context> context, Local<Value> key,
                             ^
/home/genesis/.node-gyp/9.0.0/include/node/v8config.h:318:3: note: in definition of macro ‘V8_DEPRECATED’
   declarator __attribute__((deprecated(message)))
   ^
In file included from ../src/crypto_aead.cc:9:0:
../src/crypto_aead.cc: In function ‘Nan::NAN_METHOD_RETURN_TYPE bind_crypto_aead_aes256gcm_encrypt_detached(Nan::NAN_METHOD_ARGS_TYPE)’:
../src/include/crypto_aead.h:106:92: error: no matching function for call to ‘v8::Object::ForceSet(v8::Local<v8::String>, v8::Local<v8::Object>&, v8::PropertyAttribute)’
             result->ForceSet(Nan::New<String>("cipherText").ToLocalChecked(), c, DontDelete); \
                                                                                            ^
../src/crypto_aead.cc:516:1: note: in expansion of macro ‘CRYPTO_AEAD_DETACHED_DEF’
 CRYPTO_AEAD_DETACHED_DEF(aes256gcm)
 ^
In file included from /home/genesis/.node-gyp/9.0.0/include/node/v8.h:26:0,
                 from /home/genesis/.node-gyp/9.0.0/include/node/node.h:63,
                 from ../src/include/node_sodium.h:11,
                 from ../src/crypto_aead.cc:8:
/home/genesis/.node-gyp/9.0.0/include/node/v8.h:3115:29: note: candidate: v8::Maybe<bool> v8::Object::ForceSet(v8::Local<v8::Context>, v8::Local<v8::Value>, v8::Local<v8::Value>, v8::PropertyAttribute)
                 Maybe<bool> ForceSet(Local<Context> context, Local<Value> key,
                             ^
/home/genesis/.node-gyp/9.0.0/include/node/v8config.h:318:3: note: in definition of macro ‘V8_DEPRECATED’
   declarator __attribute__((deprecated(message)))
   ^
/home/genesis/.node-gyp/9.0.0/include/node/v8.h:3115:29: note:   no known conversion for argument 3 from ‘v8::PropertyAttribute’ to ‘v8::Local<v8::Value>’
                 Maybe<bool> ForceSet(Local<Context> context, Local<Value> key,
                             ^
/home/genesis/.node-gyp/9.0.0/include/node/v8config.h:318:3: note: in definition of macro ‘V8_DEPRECATED’
   declarator __attribute__((deprecated(message)))
   ^
In file included from ../src/crypto_aead.cc:9:0:
../src/include/crypto_aead.h:107:87: error: no matching function for call to ‘v8::Object::ForceSet(v8::Local<v8::String>, v8::Local<v8::Object>&, v8::PropertyAttribute)’
             result->ForceSet(Nan::New<String>("mac").ToLocalChecked(), mac, DontDelete); \
                                                                                       ^
../src/crypto_aead.cc:516:1: note: in expansion of macro ‘CRYPTO_AEAD_DETACHED_DEF’
 CRYPTO_AEAD_DETACHED_DEF(aes256gcm)
 ^
In file included from /home/genesis/.node-gyp/9.0.0/include/node/v8.h:26:0,
                 from /home/genesis/.node-gyp/9.0.0/include/node/node.h:63,
                 from ../src/include/node_sodium.h:11,
                 from ../src/crypto_aead.cc:8:
/home/genesis/.node-gyp/9.0.0/include/node/v8.h:3115:29: note: candidate: v8::Maybe<bool> v8::Object::ForceSet(v8::Local<v8::Context>, v8::Local<v8::Value>, v8::Local<v8::Value>, v8::PropertyAttribute)
                 Maybe<bool> ForceSet(Local<Context> context, Local<Value> key,
                             ^
/home/genesis/.node-gyp/9.0.0/include/node/v8config.h:318:3: note: in definition of macro ‘V8_DEPRECATED’
   declarator __attribute__((deprecated(message)))
   ^
/home/genesis/.node-gyp/9.0.0/include/node/v8.h:3115:29: note:   no known conversion for argument 3 from ‘v8::PropertyAttribute’ to ‘v8::Local<v8::Value>’
                 Maybe<bool> ForceSet(Local<Context> context, Local<Value> key,
                             ^
/home/genesis/.node-gyp/9.0.0/include/node/v8config.h:318:3: note: in definition of macro ‘V8_DEPRECATED’
   declarator __attribute__((deprecated(message)))
   ^
In file included from ../src/crypto_aead.cc:9:0:
../src/crypto_aead.cc: In function ‘Nan::NAN_METHOD_RETURN_TYPE bind_crypto_aead_chacha20poly1305_encrypt_detached(Nan::NAN_METHOD_ARGS_TYPE)’:
../src/include/crypto_aead.h:106:92: error: no matching function for call to ‘v8::Object::ForceSet(v8::Local<v8::String>, v8::Local<v8::Object>&, v8::PropertyAttribute)’
             result->ForceSet(Nan::New<String>("cipherText").ToLocalChecked(), c, DontDelete); \
                                                                                            ^
../src/crypto_aead.cc:547:1: note: in expansion of macro ‘CRYPTO_AEAD_DETACHED_DEF’
 CRYPTO_AEAD_DETACHED_DEF(chacha20poly1305)
 ^
In file included from /home/genesis/.node-gyp/9.0.0/include/node/v8.h:26:0,
                 from /home/genesis/.node-gyp/9.0.0/include/node/node.h:63,
                 from ../src/include/node_sodium.h:11,
                 from ../src/crypto_aead.cc:8:
/home/genesis/.node-gyp/9.0.0/include/node/v8.h:3115:29: note: candidate: v8::Maybe<bool> v8::Object::ForceSet(v8::Local<v8::Context>, v8::Local<v8::Value>, v8::Local<v8::Value>, v8::PropertyAttribute)
                 Maybe<bool> ForceSet(Local<Context> context, Local<Value> key,
                             ^
/home/genesis/.node-gyp/9.0.0/include/node/v8config.h:318:3: note: in definition of macro ‘V8_DEPRECATED’
   declarator __attribute__((deprecated(message)))
   ^
/home/genesis/.node-gyp/9.0.0/include/node/v8.h:3115:29: note:   no known conversion for argument 3 from ‘v8::PropertyAttribute’ to ‘v8::Local<v8::Value>’
                 Maybe<bool> ForceSet(Local<Context> context, Local<Value> key,
                             ^
/home/genesis/.node-gyp/9.0.0/include/node/v8config.h:318:3: note: in definition of macro ‘V8_DEPRECATED’
   declarator __attribute__((deprecated(message)))
   ^
In file included from ../src/crypto_aead.cc:9:0:
../src/include/crypto_aead.h:107:87: error: no matching function for call to ‘v8::Object::ForceSet(v8::Local<v8::String>, v8::Local<v8::Object>&, v8::PropertyAttribute)’
             result->ForceSet(Nan::New<String>("mac").ToLocalChecked(), mac, DontDelete); \
                                                                                       ^
../src/crypto_aead.cc:547:1: note: in expansion of macro ‘CRYPTO_AEAD_DETACHED_DEF’
 CRYPTO_AEAD_DETACHED_DEF(chacha20poly1305)
 ^
In file included from /home/genesis/.node-gyp/9.0.0/include/node/v8.h:26:0,
                 from /home/genesis/.node-gyp/9.0.0/include/node/node.h:63,
                 from ../src/include/node_sodium.h:11,
                 from ../src/crypto_aead.cc:8:
/home/genesis/.node-gyp/9.0.0/include/node/v8.h:3115:29: note: candidate: v8::Maybe<bool> v8::Object::ForceSet(v8::Local<v8::Context>, v8::Local<v8::Value>, v8::Local<v8::Value>, v8::PropertyAttribute)
                 Maybe<bool> ForceSet(Local<Context> context, Local<Value> key,
                             ^
/home/genesis/.node-gyp/9.0.0/include/node/v8config.h:318:3: note: in definition of macro ‘V8_DEPRECATED’
   declarator __attribute__((deprecated(message)))
   ^
/home/genesis/.node-gyp/9.0.0/include/node/v8.h:3115:29: note:   no known conversion for argument 3 from ‘v8::PropertyAttribute’ to ‘v8::Local<v8::Value>’
                 Maybe<bool> ForceSet(Local<Context> context, Local<Value> key,
                             ^
/home/genesis/.node-gyp/9.0.0/include/node/v8config.h:318:3: note: in definition of macro ‘V8_DEPRECATED’
   declarator __attribute__((deprecated(message)))
   ^
In file included from ../src/crypto_aead.cc:9:0:
../src/crypto_aead.cc: In function ‘Nan::NAN_METHOD_RETURN_TYPE bind_crypto_aead_chacha20poly1305_ietf_encrypt_detached(Nan::NAN_METHOD_ARGS_TYPE)’:
../src/include/crypto_aead.h:106:92: error: no matching function for call to ‘v8::Object::ForceSet(v8::Local<v8::String>, v8::Local<v8::Object>&, v8::PropertyAttribute)’
             result->ForceSet(Nan::New<String>("cipherText").ToLocalChecked(), c, DontDelete); \
                                                                                            ^
../src/crypto_aead.cc:578:1: note: in expansion of macro ‘CRYPTO_AEAD_DETACHED_DEF’
 CRYPTO_AEAD_DETACHED_DEF(chacha20poly1305_ietf)
 ^
In file included from /home/genesis/.node-gyp/9.0.0/include/node/v8.h:26:0,
                 from /home/genesis/.node-gyp/9.0.0/include/node/node.h:63,
                 from ../src/include/node_sodium.h:11,
                 from ../src/crypto_aead.cc:8:
/home/genesis/.node-gyp/9.0.0/include/node/v8.h:3115:29: note: candidate: v8::Maybe<bool> v8::Object::ForceSet(v8::Local<v8::Context>, v8::Local<v8::Value>, v8::Local<v8::Value>, v8::PropertyAttribute)
                 Maybe<bool> ForceSet(Local<Context> context, Local<Value> key,
                             ^
/home/genesis/.node-gyp/9.0.0/include/node/v8config.h:318:3: note: in definition of macro ‘V8_DEPRECATED’
   declarator __attribute__((deprecated(message)))
   ^
/home/genesis/.node-gyp/9.0.0/include/node/v8.h:3115:29: note:   no known conversion for argument 3 from ‘v8::PropertyAttribute’ to ‘v8::Local<v8::Value>’
                 Maybe<bool> ForceSet(Local<Context> context, Local<Value> key,
                             ^
/home/genesis/.node-gyp/9.0.0/include/node/v8config.h:318:3: note: in definition of macro ‘V8_DEPRECATED’
   declarator __attribute__((deprecated(message)))
   ^
In file included from ../src/crypto_aead.cc:9:0:
../src/include/crypto_aead.h:107:87: error: no matching function for call to ‘v8::Object::ForceSet(v8::Local<v8::String>, v8::Local<v8::Object>&, v8::PropertyAttribute)’
             result->ForceSet(Nan::New<String>("mac").ToLocalChecked(), mac, DontDelete); \
                                                                                       ^
../src/crypto_aead.cc:578:1: note: in expansion of macro ‘CRYPTO_AEAD_DETACHED_DEF’
 CRYPTO_AEAD_DETACHED_DEF(chacha20poly1305_ietf)
 ^
In file included from /home/genesis/.node-gyp/9.0.0/include/node/v8.h:26:0,
                 from /home/genesis/.node-gyp/9.0.0/include/node/node.h:63,
                 from ../src/include/node_sodium.h:11,
                 from ../src/crypto_aead.cc:8:
/home/genesis/.node-gyp/9.0.0/include/node/v8.h:3115:29: note: candidate: v8::Maybe<bool> v8::Object::ForceSet(v8::Local<v8::Context>, v8::Local<v8::Value>, v8::Local<v8::Value>, v8::PropertyAttribute)
                 Maybe<bool> ForceSet(Local<Context> context, Local<Value> key,
                             ^
/home/genesis/.node-gyp/9.0.0/include/node/v8config.h:318:3: note: in definition of macro ‘V8_DEPRECATED’
   declarator __attribute__((deprecated(message)))
   ^
/home/genesis/.node-gyp/9.0.0/include/node/v8.h:3115:29: note:   no known conversion for argument 3 from ‘v8::PropertyAttribute’ to ‘v8::Local<v8::Value>’
                 Maybe<bool> ForceSet(Local<Context> context, Local<Value> key,
                             ^
/home/genesis/.node-gyp/9.0.0/include/node/v8config.h:318:3: note: in definition of macro ‘V8_DEPRECATED’
   declarator __attribute__((deprecated(message)))
   ^
sodium.target.mk:128: recipe for target 'Release/obj.target/sodium/src/crypto_aead.o' failed
make[1]: Leaving directory '/home/genesis/astrobot/node_modules/sodium/build'
make[1]: *** [Release/obj.target/sodium/src/crypto_aead.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/genesis/.nvm/versions/node/v9.0.0/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:258:23)
gyp ERR! stack     at emitTwo (events.js:135:13)
gyp ERR! stack     at ChildProcess.emit (events.js:224:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:12)
gyp ERR! System Linux 4.8.0-53-generic
gyp ERR! command "/home/genesis/.nvm/versions/node/v9.0.0/bin/node" "/home/genesis/.nvm/versions/node/v9.0.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/genesis/astrobot/node_modules/sodium
gyp ERR! node -v v9.0.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok 
Makefile:79: recipe for target 'nodesodium' failed
make: *** [nodesodium] Error 1
/home/genesis/astrobot/node_modules/sodium/install.js:288
            throw new Error(cmdLine + ' exited with code ' + code);
            ^

Error: make nodesodium exited with code 2
    at ChildProcess.<anonymous> (/home/genesis/astrobot/node_modules/sodium/install.js:288:19)
    at emitTwo (events.js:135:13)
    at ChildProcess.emit (events.js:224:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:209:12)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! sodium@2.0.1 install: `node install.js --install`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the sodium@2.0.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/genesis/.npm/_logs/2017-11-02T12_04_28_514Z-debug.log
```

**Comment by tomekmarchi** [comment]
Same issue here.

**Comment by paixaop** [comment]
New version released can you please test it out

**Comment by paixaop** [comment]
Branch  [node10-fix-forceset](https://github.com/paixaop/node-sodium/tree/node10-fix-forceset) to support N-API should work and fix this issue
