### ISSUE TITLE
Unable to compile on any version on Linux

### ISSUE THREAD

**Issue by pzduniak** [paixaop/node-sodium#126]
Same output on base images `node:9.2.0-alpine`, `node:9.2.0`, `node:8.9.1-alpine` and `node:8.9.1`

```make[4]: Leaving directory '/app/node_modules/sodium/deps/libsodium/src/libsodium/include'
make[4]: Entering directory '/app/node_modules/sodium/deps/libsodium/src/libsodium'
make[4]: *** No rule to make target 'crypto_scalarmult/curve25519/sandy2x/sandy2x.S', needed by 'crypto_scalarmult/curve25519/sandy2x/libsodium_la-sandy2x.lo'.  Stop.
make[4]: *** Waiting for unfinished jobs....
make[4]: Leaving directory '/app/node_modules/sodium/deps/libsodium/src/libsodium'
make[3]: Leaving directory '/app/node_modules/sodium/deps/libsodium/src/libsodium'
make[3]: *** [Makefile:3166: check-recursive] Error 1
make[2]: Leaving directory '/app/node_modules/sodium/deps/libsodium/src'
make[2]: *** [Makefile:391: check-recursive] Error 1
make[1]: *** [Makefile:503: check-recursive] Error 1
make[1]: Leaving directory '/app/node_modules/sodium/deps/libsodium'
make: *** [Makefile:65: libsodium] Error 2
/app/node_modules/sodium/install.js:288
            throw new Error(cmdLine + ' exited with code ' + code + ' signal ' + signal);
            ^

Error: make libsodium exited with code 2 signal null
    at ChildProcess.<anonymous> (/app/node_modules/sodium/install.js:288:19)
    at ChildProcess.emit (events.js:159:13)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:209:12)```

**Comment by pzduniak** [comment]
Seems to be an issue with libsodium itself.

**Comment by timm0e** [comment]
Can confirm, tried on latest Ubuntu, Debian and Manjaro

**Comment by vekexasia** [comment]
See my ticket here -> https://github.com/paixaop/node-sodium/issues/124

**Comment by paixaop** [comment]
upgrading to libsodium 1.0.15 and adding node 8 and node 9 support. will release soon

**Comment by paixaop** [comment]
New version released can you please test it out

**Comment by borisovg** [comment]
works for me on Node v6.10.3

**Comment by borisovg** [comment]
also works on Node v8.9.1
