### ISSUE TITLE
Failing to compile on Raspberry Pi

### ISSUE THREAD

**Issue by Gman0064** [paixaop/node-sodium#127]
Unable to compile on Raspberry Pi with Raspbian Stretch 9.1, NPM 5.5.1, Node 8.9.1.
Libsodium is installed.

```
$ sudo npm i sodium

Error: make nodesodium exited with code null
    at ChildProcess.<anonymous> (/home/Captain/node_modules/sodium/install.js:288:19)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
npm WARN discord.js@11.2.1 requires a peer of bufferutil@^3.0.2 but none is installed. You must install peer dependencies yourself.
npm WARN discord.js@11.2.1 requires a peer of erlpack@hammerandchisel/erlpack but none is installed. You must install peer dependencies yourself.
npm WARN discord.js@11.2.1 requires a peer of opusscript@^0.0.3 but none is installed. You must install peer dependencies yourself.
npm WARN discord.js@11.2.1 requires a peer of libsodium-wrappers@^0.5.4 but none is installed. You must install peer dependencies yourself.
npm WARN discord.js@11.2.1 requires a peer of uws@^0.14.5 but none is installed. You must install peer dependencies yourself.
npm WARN Captain@1.0.0 No description
npm WARN Captain@1.0.0 No repository field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! sodium@2.0.1 install: `node install.js --install`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the sodium@2.0.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2017-11-21T05_28_08_665Z-debug.log
```

**Comment by paixaop** [comment]
the package will compile its own libsodium, but currently node 8 is not supported. I'm upgrading to libsodium 1.0.15 and adding Node 8 and Node 9 support. please hang tight

**Comment by paixaop** [comment]
New version released can you please test it out

**Comment by Gman0064** [comment]
```
~$ sudo npm i sodium

/home/Captain/node_modules/sodium/install.js:288
            throw new Error(cmdLine + ' exited with code ' + code);
            ^

Error: make nodesodium exited with code null
    at ChildProcess.<anonymous> (/home/Captain/node_modules/sodium/install.js:288:19)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
npm WARN discord.js@11.2.1 requires a peer of bufferutil@^3.0.2 but none is installed. You mu                                   st install peer dependencies yourself.
npm WARN discord.js@11.2.1 requires a peer of erlpack@hammerandchisel/erlpack but none is ins                                   talled. You must install peer dependencies yourself.
npm WARN discord.js@11.2.1 requires a peer of opusscript@^0.0.3 but none is installed. You mu                                   st install peer dependencies yourself.
npm WARN discord.js@11.2.1 requires a peer of libsodium-wrappers@^0.5.4 but none is installed                                   . You must install peer dependencies yourself.
npm WARN discord.js@11.2.1 requires a peer of uws@^0.14.5 but none is installed. You must ins                                   tall peer dependencies yourself.
npm WARN Captain@1.0.0 No description
npm WARN Captain@1.0.0 No repository field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! sodium@2.0.1 install: `node install.js --install`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the sodium@2.0.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output a                                   bove.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2017-11-23T04_48_21_514Z-debug.log
```

It is still failing to compile, but it wants to still compile sodium 2.0.1.
It does however successfully compile on my Windows Machine with Node 8.7.0 and Npm 5.4.2

Pi NPM v5.5.1
Pi Node.js v8.9.1

**Comment by alexantao** [comment]
Any news about this issue ? I'm also with this problem, trying to install a homebdridge-plugin that needs sodium. It's on Raspberry PI The version it's trying to compile is 2.0.3. The error is exactly the same as above, but before that, it gives this error:
`install: info lifecycle sodium@2.0.3~install: Failed to exec install script`

**Comment by Gman0064** [comment]
> Any news about this issue ? I'm also with this problem, trying to install a homebdridge-plugin that needs sodium. It's on Raspberry PI The version it's trying to compile is 2.0.3. The error is exactly the same as above, but before that, it gives this error:
> `install: info lifecycle sodium@2.0.3~install: Failed to exec install script`
> 
> Obs.: node 10.15.1, npm 6.4.1

I've since abandoned this project and moved it to another machine for development. Above mentioned fix by @paixaop never worked.
