### ISSUE TITLE
FreeBSD support

### ISSUE THREAD

**Issue by jpawlowski** [paixaop/node-sodium#132]
it seems to me the makefile does not consider FreeBSD as an operating system:

````
make: Fatal errors encountered -- cannot continue/usr/local/lib/node_modules/sodium/install.js:287
            throw new Error(cmdLine + ' exited with code ' + code);
            ^

Error: make libsodium exited with code 1
    at ChildProcess.<anonymous> (/usr/local/lib/node_modules/sodium/install.js:287:19)
    at ChildProcess.emit (events.js:180:13)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:209:12)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! sodium@2.0.3 preinstall: `node install.js --preinstall`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the sodium@2.0.3 preinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2018-04-08T13_56_27_209Z-debug.log
root@hostname:~ # uname -a
FreeBSD hostname 11.1-RELEASE-p8 FreeBSD 11.1-RELEASE-p8  76d691b36(stable/18.1)  amd64
````

Would you mind adding FreeBSD to the list of OS?

**Comment by paixaop** [comment]
What version of make are you using?

**Comment by A2-Dev** [comment]
same issue

 # pkg info | grep make
automake-1.16.1                GNU Standards-compliant Makefile generator
gmake-4.2.1_2                  GNU version of 'make' utility

pkg updated and upgraded and running latest node/npm updated and upgraded as well -g

**Comment by redxtech** [comment]
Can confirm this is still an issue. Would really appreciate FreeBSD support.

Output of `uname -a`:
`FreeBSD hostname 12.2-RELEASE-p11 FreeBSD 12.2-RELEASE-p11 75566f060d4(HEAD) TRUENAS  amd64`

Output of `pkg info | grep make`:

`gmake-4.3_2   GNU version of 'make' utility`
