### ISSUE TITLE
node-sodium install fail on Ubuntu

### ISSUE THREAD

**Issue by BenReilly** [paixaop/node-sodium#133]
I am using Ubuntu 18..04. it's a new install. I'm also fairly unfamiliar with linux so I'm prepared to accept that I just did something stupid.

Nodejs 8.10.0
npm 3.5.2

I installed node-gyp and libsodium globally. node sodium is having issues tho.

Here's what I get from npm install --unsaf-perm. Same results when I sudo. 

```
> sodium@2.0.3 preinstall /usr/local/lib/node_modules/.staging/sodium-550e4063
> node install.js --preinstall

Static libsodium was not found at /usr/local/lib/node_modules/.staging/sodium-550e4063/deps/build/lib/libsodium so compiling libsodium from source.
autoconf is required, but wasn't found on this system
Makefile:61: recipe for target 'libsodium' failed
make: *** [libsodium] Error 1
/usr/local/lib/node_modules/.staging/sodium-550e4063/install.js:287
            throw new Error(cmdLine + ' exited with code ' + code);
            ^

Error: make libsodium exited with code 2
    at ChildProcess.<anonymous> (/usr/local/lib/node_modules/.staging/sodium-550e4063/install.js:287:19)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
npm ERR! Linux 4.15.0-23-generic
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "install" "sodium" "-g" "--unsafe-perm"
npm ERR! node v8.10.0
npm ERR! npm  v3.5.2
npm ERR! code ELIFECYCLE

npm ERR! sodium@2.0.3 preinstall: `node install.js --preinstall`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the sodium@2.0.3 preinstall script 'node install.js --preinstall'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the sodium package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node install.js --preinstall
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs sodium
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls sodium
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /usr/local/lib/npm-debug.log

```
i have run `sudo apt-get install libtool-bin` but it doesn't change anything.

**Comment by a1300** [comment]
I don't know if that helps, but I couldn't compile `sodium` on ubuntu 18.04 when there was a `_` space somewhere in the path of the project.
e.g. `/home/user/my projects/project/`

**Comment by jedisct1** [comment]
Autotools don't like directories with spaces.

**Comment by ZombyMedia** [comment]
I have the same problem.
sodium is always failing on Ubuntu 16.04

No clue how to avid this problem
