### ISSUE TITLE
Cant install sodium on my Pi

### ISSUE THREAD

**Issue by CatFlaps5** [paixaop/node-sodium#145]
> sodium@3.0.2 preinstall /home/pi/Discord/Parallax/node_modules/sodium
> node install.js --preinstall

Static libsodium was not found at /home/pi/Discord/Parallax/node_modules/sodium/deps/build/lib/libsodium so compiling libsodium from source.
libtool is required, but wasn't found on this system
Makefile:61: recipe for target 'libsodium' failed
make: *** [libsodium] Error 1
/home/pi/Discord/Parallax/node_modules/sodium/install.js:293
            throw new Error(cmdLine + ' exited with code ' + code);
            ^

Error: make libsodium exited with code 2
    at ChildProcess.<anonymous> (/home/pi/Discord/Parallax/node_modules/sodium/install.js:293:19)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
npm WARN This failure might be due to the use of legacy binary "node"
npm WARN For further explanations, please read
/usr/share/doc/nodejs/README.Debian

npm ERR! sodium@3.0.2 preinstall: `node install.js --preinstall`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the sodium@3.0.2 preinstall script.
npm ERR! This is most likely a problem with the sodium package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node install.js --preinstall
npm ERR! You can get their info via:
npm ERR!     npm owner ls sodium
npm ERR! There is likely additional logging output above.

npm ERR! System Linux 4.9.41-v7+
npm ERR! command "/usr/bin/node" "/usr/bin/npm" "install" "sodium"
npm ERR! cwd /home/pi/Discord/Parallax
npm ERR! node -v v8.11.1
npm ERR! npm -v 1.4.21
npm ERR! code ELIFECYCLE
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     /home/pi/Discord/Parallax/npm-debug.log
npm ERR! not ok code 0

**Comment by schw3i** [comment]
> libtool is required, but wasn't found on this system

You need to install libtool on your Pi

**Comment by rawr51919** [comment]
Ye. This is an error that only happened because of the absence of libtool. Make sure you have it and retry the install. @CatFlaps5, it's OK to close this as this isn't an issue with the repo itself, but rather with an unmet dependency
