### ISSUE TITLE
Error installing on Windows

### ISSUE THREAD

**Issue by brilvio** [paixaop/node-sodium#150]
Trying to install sodium on windows gave me an error:

```shell
npm install sodium

> sodium@3.0.2 preinstall G:\Projetos\podbot\node_modules\sodium
> node install.js --preinstall

MS Version: 2015
Preinstall Mode
Download libsodium.lib
MS Version: 2015
Platform Tool is v140
Download: https://raw.githubusercontent.com/paixaop/libsodium-bin/master/1.0.16/x64/Release/v140/dynamic/libsodium.dll
Download: https://raw.githubusercontent.com/paixaop/libsodium-bin/master/1.0.16/x64/Release/v140/dynamic/libsodium.exp
Download: https://raw.githubusercontent.com/paixaop/libsodium-bin/master/1.0.16/x64/Release/v140/dynamic/libsodium.lib
Download: https://raw.githubusercontent.com/paixaop/libsodium-bin/master/1.0.16/x64/Release/v140/dynamic/libsodium.pdb
Libs for version v140 downloaded.
Download: https://raw.githubusercontent.com/paixaop/libsodium-bin/master/1.0.16/include/sodium/core.h
Download: https://raw.githubusercontent.com/paixaop/libsodium-bin/master/1.0.16/include/sodium/crypto_aead_aes256gcm.h
Download: https://raw.githubusercontent.com/paixaop/libsodium-bin/master/1.0.16/include/sodium/crypto_aead_chacha20poly1305.h
Download: https://raw.githubusercontent.com/paixaop/libsodium-bin/master/1.0.16/include/sodium/crypto_aead_xchacha20poly1305.h
Download: https://raw.githubusercontent.com/paixaop/libsodium-bin/master/1.0.16/include/sodium/crypto_auth.h
Download: https://raw.githubusercontent.com/paixaop/libsodium-bin/master/1.0.16/include/sodium/crypto_auth_hmacsha256.h
Download: https://raw.githubusercontent.com/paixaop/libsodium-bin/master/1.0.16/include/sodium/crypto_auth_hmacsha512.h
Download: https://raw.githubusercontent.com/paixaop/libsodium-bin/master/1.0.16/include/sodium/crypto_auth_hmacsha512256.h
Download: https://raw.githubusercontent.com/paixaop/libsodium-bin/master/1.0.16/include/sodium/crypto_box.h
Download: https://raw.githubusercontent.com/paixaop/libsodium-bin/master/1.0.16/include/sodium/crypto_box_curve25519xchacha20poly1305.h
Download: https://raw.githubusercontent.com/paixaop/libsodium-bin/master/1.0.16/include/sodium/crypto_box_curve25519xsalsa20poly1305.h
Download: https://raw.githubusercontent.com/paixaop/libsodium-bin/master/1.0.16/include/sodium/crypto_core_ed25519.h
Download: https://raw.githubusercontent.com/paixaop/libsodium-bin/master/1.0.16/include/sodium/crypto_core_hchacha20.h
Download: https://raw.githubusercontent.com/paixaop/libsodium-bin/master/1.0.16/include/sodium/crypto_core_hsalsa20.h
Download: https://raw.githubusercontent.com/paixaop/libsodium-bin/master/1.0.16/include/sodium/crypto_core_salsa20.h
Download: https://raw.githubusercontent.com/paixaop/libsodium-bin/master/1.0.16/include/sodium/crypto_core_salsa2012.h
Download: https://raw.githubusercontent.com/paixaop/libsodium-bin/master/1.0.16/include/sodium/crypto_core_salsa208.h
Download: https://raw.githubusercontent.com/paixaop/libsodium-bin/master/1.0.16/include/sodium/crypto_generichash.h
Download: https://raw.githubusercontent.com/paixaop/libsodium-bin/master/1.0.16/include/sodium/crypto_generichash_blake2b.h
Download: https://raw.githubusercontent.com/paixaop/libsodium-bin/master/1.0.16/include/sodium/crypto_hash.h
Download: https://raw.githubusercontent.com/paixaop/libsodium-bin/master/1.0.16/include/sodium/crypto_hash_sha256.h
Download: https://raw.githubusercontent.com/paixaop/libsodium-bin/master/1.0.16/include/sodium/crypto_hash_sha512.h
Download: https://raw.githubusercontent.com/paixaop/libsodium-bin/master/1.0.16/include/sodium/crypto_kdf.h
Download: https://raw.githubusercontent.com/paixaop/libsodium-bin/master/1.0.16/include/sodium/crypto_kdf_blake2b.h
Download: https://raw.githubusercontent.com/paixaop/libsodium-bin/master/1.0.16/include/sodium/crypto_kx.h
Download: https://raw.githubusercontent.com/paixaop/libsodium-bin/master/1.0.16/include/sodium/crypto_onetimeauth.h
Download: https://raw.githubusercontent.com/paixaop/libsodium-bin/master/1.0.16/include/sodium/crypto_onetimeauth_poly1305.h
fs.js:144
    throw new ERR_INVALID_CALLBACK();
    ^

TypeError [ERR_INVALID_CALLBACK]: Callback must be a function
    at makeCallback (fs.js:144:11)
    at Object.unlink (fs.js:959:14)
    at ClientRequest.<anonymous> (G:\Projetos\podbot\node_modules\sodium\install.js:149:12)
    at ClientRequest.emit (events.js:182:13)
    at TLSSocket.socketErrorListener (_http_client.js:399:9)
    at TLSSocket.emit (events.js:182:13)
    at emitErrorNT (internal/streams/destroy.js:82:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)
    at process.internalTickCallback (internal/process/next_tick.js:72:19)
```

**Comment by michaelrommel** [comment]
Same error here on Windows 10, node v12.2.0
