### ISSUE TITLE
Can't install sodium, please help me (Windows)

### ISSUE THREAD

**Issue by nashwik** [paixaop/node-sodium#172]
Hello, i can't install sodium (with `npm install sodium`)

The error:
```js
0 verbose cli [
0 verbose cli   'V:\\Developpement\\Logiciel\\nodejs\\node.exe',
0 verbose cli   'V:\\Developpement\\Logiciel\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
0 verbose cli   'i',
0 verbose cli   'sodium'
0 verbose cli ]
1 info using npm@7.21.1
2 info using node@v16.9.1
3 timing npm:load:whichnode Completed in 0ms
4 timing config:load:defaults Completed in 1ms
5 timing config:load:file:V:\Developpement\Logiciel\nodejs\node_modules\npm\npmrc Completed in 2ms
6 timing config:load:builtin Completed in 2ms
7 timing config:load:cli Completed in 1ms
8 timing config:load:env Completed in 1ms
9 timing config:load:file:C:\Users\Basti\Desktop\MyProject\_GithubProjects\useMyMusicBot\.npmrc Completed in 0ms
10 timing config:load:project Completed in 1ms
11 timing config:load:file:C:\Users\Basti\.npmrc Completed in 0ms
12 timing config:load:user Completed in 0ms
13 timing config:load:file:C:\Users\Basti\AppData\Roaming\npm\etc\npmrc Completed in 0ms
14 timing config:load:global Completed in 0ms
15 timing config:load:validate Completed in 1ms
16 timing config:load:credentials Completed in 0ms
17 timing config:load:setEnvs Completed in 1ms
18 timing config:load Completed in 9ms
19 timing npm:load:configload Completed in 9ms
20 timing npm:load:setTitle Completed in 0ms
21 timing npm:load:setupLog Completed in 1ms
22 timing config:load:flatten Completed in 2ms
23 timing npm:load:cleanupLog Completed in 2ms
24 timing npm:load:configScope Completed in 0ms
25 timing npm:load:projectScope Completed in 1ms
26 timing npm:load Completed in 16ms
27 timing arborist:ctor Completed in 2ms
28 timing idealTree:init Completed in 64ms
29 timing idealTree:userRequests Completed in 2ms
30 silly idealTree buildDeps
31 silly fetch manifest sodium@*
32 verbose shrinkwrap failed to load node_modules/.package-lock.json out of date, updated: node_modules
33 http fetch GET 200 https://registry.npmjs.org/sodium 830ms (cache revalidated)
34 silly placeDep ROOT sodium@3.0.2 OK for: usemymusicbot@0.0.1 want: *
35 timing idealTree:#root Completed in 836ms
36 timing idealTree:node_modules/sodium Completed in 0ms
37 timing idealTree:buildDeps Completed in 836ms
38 timing idealTree:fixDepFlags Completed in 2ms
39 timing idealTree Completed in 906ms
40 timing reify:loadTrees Completed in 907ms
41 timing reify:diffTrees Completed in 9ms
42 silly reify moves {}
43 timing reify:retireShallow Completed in 0ms
44 timing reify:createSparse Completed in 2ms
45 timing reify:loadBundles Completed in 0ms
46 silly audit bulk request {
46 silly audit   '@derhuerst/http-basic': [ '8.2.1' ],
46 silly audit   '@discordjs/builders': [ '0.5.0' ],
46 silly audit   '@discordjs/collection': [ '0.2.1' ],
46 silly audit   '@discordjs/form-data': [ '3.0.1' ],
46 silly audit   '@discordjs/node-pre-gyp': [ '0.4.1' ],
46 silly audit   '@discordjs/opus': [ '0.6.0', '0.5.3' ],
46 silly audit   '@discordjs/voice': [ '0.6.0' ],
46 silly audit   'node-addon-api': [ '3.2.1', '4.2.0' ],
46 silly audit   'prism-media': [ '1.3.2' ],
46 silly audit   '@sapphire/async-queue': [ '1.1.4' ],
46 silly audit   '@sindresorhus/is': [ '4.2.0' ],
46 silly audit   '@types/node': [ '16.9.2', '10.17.60' ],
46 silly audit   '@types/ws': [ '7.4.7' ],
46 silly audit   abbrev: [ '1.1.1' ],
46 silly audit   'agent-base': [ '6.0.2' ],
46 silly audit   'ansi-regex': [ '3.0.0' ],
46 silly audit   'ansi-styles': [ '4.3.0' ],
46 silly audit   aproba: [ '2.0.0' ],
46 silly audit   'are-we-there-yet': [ '2.0.0' ],
46 silly audit   'readable-stream': [ '3.6.0', '2.3.7' ],
46 silly audit   asynckit: [ '0.4.0' ],
46 silly audit   'balanced-match': [ '1.0.2' ],
46 silly audit   'brace-expansion': [ '1.1.11' ],
46 silly audit   'buffer-from': [ '1.1.2' ],
46 silly audit   callsites: [ '3.1.0' ],
46 silly audit   caseless: [ '0.12.0' ],
46 silly audit   chalk: [ '4.1.2' ],
46 silly audit   chownr: [ '2.0.0' ],
46 silly audit   'color-convert': [ '2.0.1' ],
46 silly audit   'color-name': [ '1.1.4' ],
46 silly audit   'color-support': [ '1.1.3' ],
46 silly audit   'combined-stream': [ '1.0.8' ],
46 silly audit   'concat-map': [ '0.0.1' ],
46 silly audit   'concat-stream': [ '1.6.2' ],
46 silly audit   'console-control-strings': [ '1.1.0' ],
46 silly audit   'core-util-is': [ '1.0.3' ],
46 silly audit   debug: [ '4.3.2' ],
46 silly audit   'delayed-stream': [ '1.0.0' ],
46 silly audit   delegates: [ '1.0.0' ],
46 silly audit   'detect-libc': [ '1.0.3' ],
46 silly audit   'discord-api-types': [ '0.22.0' ],
46 silly audit   'discord.js': [ '13.1.0' ],
46 silly audit   'dot-prop': [ '6.0.1' ],
46 silly audit   'env-paths': [ '2.2.1' ],
46 silly audit   'ffmpeg-static': [ '4.4.0' ],
46 silly audit   'fs-minipass': [ '2.1.0' ],
46 silly audit   'fs.realpath': [ '1.0.0' ],
46 silly audit   gauge: [ '3.0.1' ],
46 silly audit   glob: [ '7.1.7' ],
46 silly audit   'has-flag': [ '4.0.0' ],
46 silly audit   'has-unicode': [ '2.0.1' ],
46 silly audit   'http-response-object': [ '3.0.2' ],
46 silly audit   'https-proxy-agent': [ '5.0.0' ],
46 silly audit   inflight: [ '1.0.6' ],
46 silly audit   inherits: [ '2.0.4' ],
46 silly audit   'is-fullwidth-code-point': [ '2.0.0' ],
46 silly audit   'is-obj': [ '2.0.0' ],
46 silly audit   isarray: [ '1.0.0' ],
46 silly audit   'lodash.isequal': [ '4.5.0' ],
46 silly audit   'lru-cache': [ '6.0.0' ],
46 silly audit   m3u8stream: [ '0.8.4' ],
46 silly audit   'make-dir': [ '3.1.0' ],
46 silly audit   semver: [ '6.3.0', '7.3.5' ],
46 silly audit   'mime-db': [ '1.49.0' ],
46 silly audit   'mime-types': [ '2.1.32' ],
46 silly audit   miniget: [ '4.2.1' ],
46 silly audit   minimatch: [ '3.0.4' ],
46 silly audit   minipass: [ '3.1.5' ],
46 silly audit   minizlib: [ '2.1.2' ],
46 silly audit   mkdirp: [ '1.0.4' ],
46 silly audit   moment: [ '2.29.1' ],
46 silly audit   'moment-timezone': [ '0.5.33' ],
46 silly audit   ms: [ '2.1.2' ],
46 silly audit   'node-fetch': [ '2.6.2' ],
46 silly audit   nopt: [ '5.0.0' ],
46 silly audit   npmlog: [ '5.0.1' ],
46 silly audit   'object-assign': [ '4.1.1' ],
46 silly audit   once: [ '1.4.0' ],
46 silly audit   ow: [ '0.27.0' ],
46 silly audit   'parse-cache-control': [ '1.0.1' ],
46 silly audit   'path-is-absolute': [ '1.0.1' ],
46 silly audit   'process-nextick-args': [ '2.0.1' ],
46 silly audit   progress: [ '2.0.3' ],
46 silly audit   rimraf: [ '3.0.2' ],
46 silly audit   'safe-buffer': [ '5.1.2' ],
46 silly audit   sax: [ '1.2.4' ],
46 silly audit   'set-blocking': [ '2.0.0' ],
46 silly audit   'signal-exit': [ '3.0.4' ],
46 silly audit   string_decoder: [ '1.1.1' ],
46 silly audit   'string-width': [ '2.1.1' ],
46 silly audit   'strip-ansi': [ '4.0.0' ],
46 silly audit   'supports-color': [ '7.2.0' ],
46 silly audit   tar: [ '6.1.11' ],
46 silly audit   'tiny-typed-emitter': [ '2.1.0' ],
46 silly audit   'ts-mixer': [ '6.0.0' ],
46 silly audit   tslib: [ '2.3.1' ],
46 silly audit   'type-fest': [ '1.4.0' ],
46 silly audit   typedarray: [ '0.0.6' ],
46 silly audit   'util-deprecate': [ '1.0.2' ],
46 silly audit   'vali-date': [ '1.0.0' ],
46 silly audit   'wide-align': [ '1.1.3' ],
46 silly audit   wrappy: [ '1.0.2' ],
46 silly audit   ws: [ '7.5.5' ],
46 silly audit   yallist: [ '4.0.0' ],
46 silly audit   'ytdl-core': [ '4.9.1' ],
46 silly audit   sodium: [ '3.0.2' ]
46 silly audit }
47 http fetch POST 200 https://registry.npmjs.org/-/npm/v1/security/advisories/bulk 217ms
48 timing auditReport:getReport Completed in 219ms
49 silly audit report {}
50 timing auditReport:init Completed in 0ms
51 timing reify:audit Completed in 219ms
52 timing reifyNode:node_modules/sodium Completed in 2412ms
53 timing reify:unpack Completed in 2412ms
54 timing reify:unretire Completed in 0ms
55 timing build:queue Completed in 0ms
56 info run sodium@3.0.2 preinstall node_modules/sodium node install.js --preinstall
57 info run sodium@3.0.2 preinstall { code: 0, signal: null }
58 timing build:run:preinstall:node_modules/sodium Completed in 16823ms
59 timing build:run:preinstall Completed in 16824ms
60 info run sodium@3.0.2 install node_modules/sodium node install.js --install
61 info run sodium@3.0.2 install { code: 1, signal: null }
62 timing reify:rollback:createSparse Completed in 137ms
63 timing reify:rollback:retireShallow Completed in 0ms
64 timing command:install Completed in 27189ms
65 verbose stack Error: command failed
65 verbose stack     at ChildProcess.<anonymous> (V:\Developpement\Logiciel\nodejs\node_modules\npm\node_modules\@npmcli\promise-spawn\index.js:64:27)
65 verbose stack     at ChildProcess.emit (node:events:394:28)
65 verbose stack     at maybeClose (node:internal/child_process:1064:16)
65 verbose stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:301:5)
66 verbose pkgid sodium@3.0.2
67 verbose cwd C:\Users\Basti\Desktop\MyProject\_GithubProjects\useMyMusicBot
68 verbose Windows_NT 10.0.19043
69 verbose argv "V:\\Developpement\\Logiciel\\nodejs\\node.exe" "V:\\Developpement\\Logiciel\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "i" "sodium"
70 verbose node v16.9.1
71 verbose npm  v7.21.1
72 error code 1
73 error path C:\Users\Basti\Desktop\MyProject\_GithubProjects\useMyMusicBot\node_modules\sodium
74 error command failed
75 error command C:\WINDOWS\system32\cmd.exe /d /s /c node install.js --install
76 error MS Version: 2015
76 error Install Mode
76 error gyp info it worked if it ends with ok
76 error gyp info using node-gyp@7.1.2
76 error gyp info using node@16.9.1 | win32 | x64
76 error gyp info find Python using Python version 3.9.7 found at "C:\Users\Basti\AppData\Local\Programs\Python\Python39\python3.exe"
76 error gyp info find VS using VS2015 (14.0) found at:
76 error gyp info find VS "V:\Program Files (x86)\Microsoft Visual Studio 14.0"
76 error gyp info find VS run with --verbose for detailed information
76 error (node:36540) [DEP0150] DeprecationWarning: Setting process.config is deprecated. In the future the property will be read-only.
76 error (Use `node --trace-deprecation ...` to show where the warning was created)
76 error gyp info spawn C:\Users\Basti\AppData\Local\Programs\Python\Python39\python3.exe
76 error gyp info spawn args [
76 error gyp info spawn args   'V:\\Developpement\\Logiciel\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\gyp\\gyp_main.py',
76 error gyp info spawn args   'binding.gyp',
76 error gyp info spawn args   '-f',
76 error gyp info spawn args   'msvs',
76 error gyp info spawn args   '-I',
76 error gyp info spawn args   'C:\\Users\\Basti\\Desktop\\MyProject\\_GithubProjects\\useMyMusicBot\\node_modules\\sodium\\build\\config.gypi',
76 error gyp info spawn args   '-I',
76 error gyp info spawn args   'V:\\Developpement\\Logiciel\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\addon.gypi',
76 error gyp info spawn args   '-I',
76 error gyp info spawn args   'C:\\Users\\Basti\\AppData\\Local\\node-gyp\\Cache\\16.9.1\\include\\node\\common.gypi',
76 error gyp info spawn args   '-Dlibrary=shared_library',
76 error gyp info spawn args   '-Dvisibility=default',
76 error gyp info spawn args   '-Dnode_root_dir=C:\\Users\\Basti\\AppData\\Local\\node-gyp\\Cache\\16.9.1',
76 error gyp info spawn args   '-Dnode_gyp_dir=V:\\Developpement\\Logiciel\\nodejs\\node_modules\\npm\\node_modules\\node-gyp',
76 error gyp info spawn args   '-Dnode_lib_file=C:\\\\Users\\\\Basti\\\\AppData\\\\Local\\\\node-gyp\\\\Cache\\\\16.9.1\\\\<(target_arch)\\\\node.lib',
76 error gyp info spawn args   '-Dmodule_root_dir=C:\\Users\\Basti\\Desktop\\MyProject\\_GithubProjects\\useMyMusicBot\\node_modules\\sodium',
76 error gyp info spawn args   '-Dnode_engine=v8',
76 error gyp info spawn args   '--depth=.',
76 error gyp info spawn args   '--no-parallel',
76 error gyp info spawn args   '--generator-output',
76 error gyp info spawn args   'C:\\Users\\Basti\\Desktop\\MyProject\\_GithubProjects\\useMyMusicBot\\node_modules\\sodium\\build',
76 error gyp info spawn args   '-Goutput_dir=.'
76 error gyp info spawn args ]
76 error gyp info spawn C:\Program Files (x86)\MSBuild\14.0\bin\MSBuild.exe
76 error gyp info spawn args [
76 error gyp info spawn args   'build/binding.sln',
76 error gyp info spawn args   '/clp:Verbosity=minimal',
76 error gyp info spawn args   '/nologo',
76 error gyp info spawn args   '/p:Configuration=Release;Platform=x64'
76 error gyp info spawn args ]
76 error Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
76 error C:\Users\Basti\Desktop\MyProject\_GithubProjects\useMyMusicBot\node_modules\sodium\node-addon-api\nothing.vcxproj(20,3): error MSB4019: The imported project "C:\Microsoft.Cpp.Default.props" was not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk.
76 error gyp ERR! build error
76 error gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\MSBuild.exe` failed with exit code: 1
76 error gyp ERR! stack     at ChildProcess.onExit (V:\Developpement\Logiciel\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:194:23)
76 error gyp ERR! stack     at ChildProcess.emit (node:events:394:28)
76 error gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:290:12)
76 error gyp ERR! System Windows_NT 10.0.19043
76 error gyp ERR! command "V:\\Developpement\\Logiciel\\nodejs\\node.exe" "V:\\Developpement\\Logiciel\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
76 error gyp ERR! cwd C:\Users\Basti\Desktop\MyProject\_GithubProjects\useMyMusicBot\node_modules\sodium
76 error gyp ERR! node -v v16.9.1
76 error gyp ERR! node-gyp -v v7.1.2
76 error gyp ERR! not ok
77 error C:\Users\Basti\Desktop\MyProject\_GithubProjects\useMyMusicBot\node_modules\sodium\install.js:293
77 error             throw new Error(cmdLine + ' exited with code ' + code);
77 error             ^
77 error
77 error Error: node-gyp rebuild exited with code 1
77 error     at ChildProcess.<anonymous> (C:\Users\Basti\Desktop\MyProject\_GithubProjects\useMyMusicBot\node_modules\sodium\install.js:293:19)
77 error     at ChildProcess.emit (node:events:394:28)
77 error     at Process.ChildProcess._handle.onexit (node:internal/child_process:290:12)
78 verbose exit 1
```

**Comment by iabdo9** [comment]
Found a solution?
