### ISSUE TITLE
No longer builds against Node v0.12.0

### ISSUE THREAD

**Issue by ericbarch** [paixaop/node-sodium#32]
Trying to build on Darwin. Here's my output (at least where things get interesting):

<pre>
pto_scalarmult/curve25519/donna_c64/smult_curve25519_donna_c64.o
  LIBTOOL-STATIC Release/sodium.a
  CXX(target) Release/obj.target/sodium/sodium.o
../sodium.cc:24:36: error: no member named 'GetCurrent' in 'v8::Context'
Local<Object> globalObj = Context::GetCurrent()->Global();
                          ~~~~~~~~~^
../sodium.cc:28:53: error: no member named 'New' in 'v8::String'
       Local<Function>::Cast(globalObj->Get(String::New("Buffer")));
                                            ~~~~~~~~^
../sodium.cc:90:52: error: no member named 'New' in 'v8::String'
    return ThrowException(Exception::Error(String::New(msg)));
                                           ~~~~~~~~^
../sodium.cc:94:48: error: unknown type name 'Arguments'; did you mean
      'v8::internal::Arguments'?
Handle<Value> bind_sodium_version_string(const Arguments& args) {
                                               ^~~~~~~~~
                                               v8::internal::Arguments
/Users/ebarch/.node-gyp/0.12.0/deps/v8/include/v8.h:127:7: note:
      'v8::internal::Arguments' declared here
class Arguments;
      ^
../sodium.cc:95:17: error: calling a protected constructor of class
      'v8::HandleScope'
    HandleScope scope;
                ^
/Users/ebarch/.node-gyp/0.12.0/deps/v8/include/v8.h:816:13: note: declared
      protected here
  V8_INLINE HandleScope() {}
            ^
../sodium.cc:96:18: error: no member named 'Close' in 'v8::HandleScope'
    return scope.Close(
           ~~~~~ ^
../sodium.cc:97:17: error: no member named 'New' in 'v8::String'
        String::New(sodium_version_string())
        ~~~~~~~~^
../sodium.cc:101:55: error: unknown type name 'Arguments'; did you mean
      'v8::internal::Arguments'?
Handle<Value> bind_sodium_library_version_minor(const Arguments& args) {
                                                      ^~~~~~~~~
                                                      v8::internal::Arguments
/Users/ebarch/.node-gyp/0.12.0/deps/v8/include/v8.h:127:7: note:
      'v8::internal::Arguments' declared here
class Arguments;
      ^
../sodium.cc:102:17: error: calling a protected constructor of class
      'v8::HandleScope'
    HandleScope scope;
                ^
/Users/ebarch/.node-gyp/0.12.0/deps/v8/include/v8.h:816:13: note: declared
      protected here
  V8_INLINE HandleScope() {}
            ^
../sodium.cc:103:18: error: no member named 'Close' in 'v8::HandleScope'
    return scope.Close(
           ~~~~~ ^
../sodium.cc:104:52: error: too few arguments to function call, expected 2, have
      1
        Integer::New(sodium_library_version_minor())
        ~~~~~~~~~~~~                               ^
/Users/ebarch/.node-gyp/0.12.0/deps/v8/include/v8.h:2012:3: note: 'New' declared
      here
  static Local<Integer> New(Isolate* isolate, int32_t value);
  ^
../sodium.cc:108:55: error: unknown type name 'Arguments'; did you mean
      'v8::internal::Arguments'?
Handle<Value> bind_sodium_library_version_major(const Arguments& args) {
                                                      ^~~~~~~~~
                                                      v8::internal::Arguments
/Users/ebarch/.node-gyp/0.12.0/deps/v8/include/v8.h:127:7: note:
      'v8::internal::Arguments' declared here
class Arguments;
      ^
../sodium.cc:109:17: error: calling a protected constructor of class
      'v8::HandleScope'
    HandleScope scope;
                ^
/Users/ebarch/.node-gyp/0.12.0/deps/v8/include/v8.h:816:13: note: declared
      protected here
  V8_INLINE HandleScope() {}
            ^
../sodium.cc:110:18: error: no member named 'Close' in 'v8::HandleScope'
    return scope.Close(
           ~~~~~ ^
../sodium.cc:111:52: error: too few arguments to function call, expected 2, have
      1
        Integer::New(sodium_library_version_major())
        ~~~~~~~~~~~~                               ^
/Users/ebarch/.node-gyp/0.12.0/deps/v8/include/v8.h:2012:3: note: 'New' declared
      here
  static Local<Integer> New(Isolate* isolate, int32_t value);
  ^
../sodium.cc:116:34: error: unknown type name 'Arguments'; did you mean
      'v8::internal::Arguments'?
Handle<Value> bind_memzero(const Arguments& args) {
                                 ^~~~~~~~~
                                 v8::internal::Arguments
/Users/ebarch/.node-gyp/0.12.0/deps/v8/include/v8.h:127:7: note:
      'v8::internal::Arguments' declared here
class Arguments;
      ^
../sodium.cc:117:17: error: calling a protected constructor of class
      'v8::HandleScope'
    HandleScope scope;
                ^
/Users/ebarch/.node-gyp/0.12.0/deps/v8/include/v8.h:816:13: note: declared
      protected here
  V8_INLINE HandleScope() {}
            ^
../sodium.cc:119:5: error: member access into incomplete type 'const
      v8::internal::Arguments'
    NUMBER_OF_MANDATORY_ARGS(1,"argument must be a buffer");
    ^
../sodium.cc:77:13: note: expanded from macro 'NUMBER_OF_MANDATORY_ARGS'
    if (args.Length() < (n)) {                \
            ^
/Users/ebarch/.node-gyp/0.12.0/deps/v8/include/v8.h:127:7: note: forward
      declaration of 'v8::internal::Arguments'
class Arguments;
      ^
../sodium.cc:120:5: error: type 'const v8::internal::Arguments' does not provide
      a subscript operator
    GET_ARG_AS_VOID(0, buffer);
    ^~~~~~~~~~~~~~~~~~~~~~~~~~
../sodium.cc:70:5: note: expanded from macro 'GET_ARG_AS_VOID'
    GET_ARG_AS(i, NAME, void*)
    ^~~~~~~~~~~~~~~~~~~~~~~~~~
../sodium.cc:46:5: note: expanded from macro 'GET_ARG_AS'
    ARG_IS_BUFFER(i,#NAME); \
    ^~~~~~~~~~~~~~~~~~~~~~
../sodium.cc:33:34: note: expanded from macro 'ARG_IS_BUFFER'
    if (!Buffer::HasInstance(args[i])) { \
                             ~~~~^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
20 errors generated.
make: *** [Release/obj.target/sodium/sodium.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1067:12)
gyp ERR! System Darwin 14.1.0
gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! node -v v0.12.0
gyp ERR! node-gyp -v v1.0.2
gyp ERR! not ok
npm ERR! Darwin 14.1.0
npm ERR! argv "node" "/usr/local/bin/npm" "install"
npm ERR! node v0.12.0
npm ERR! npm  v2.5.1
npm ERR! code ELIFECYCLE

npm ERR! sodium@1.0.13 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the sodium@1.0.13 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the sodium package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
</pre>

**Comment by paixaop** [comment]
just merged #27 which should allow you to compile under 0.12
