### ISSUE TITLE
Can't install in Docker.

### ISSUE THREAD

**Issue by NodeGuy** [paixaop/node-sodium#39]
```
$ docker run -it --rm node:latest bash
root@b6f988506176:/# npm install sodium
-
> sodium@1.0.15 install /node_modules/sodium
> node-gyp rebuild

gyp: /node_modules/sodium/deps/libsodium.gyp not found (cwd: /node_modules/sodium) while loading dependencies of binding.gyp while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:343:16)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1074:12)
gyp ERR! System Linux 3.18.5-tinycore64
gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /node_modules/sodium
gyp ERR! node -v v0.12.3
gyp ERR! node-gyp -v v1.0.3
gyp ERR! not ok 
npm ERR! Linux 3.18.5-tinycore64
npm ERR! argv "node" "/usr/local/bin/npm" "install" "sodium"
npm ERR! node v0.12.3
npm ERR! npm  v2.10.0
npm ERR! code ELIFECYCLE

npm ERR! sodium@1.0.15 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the sodium@1.0.15 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the sodium package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls sodium
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /npm-debug.log
```

I tried installing the Debian package for `libsodium` but it didn't help:

`root@b6f988506176:/# apt-get update && apt-get install -y libsodium-dev`

**Comment by paixaop** [comment]
run `npm install` first before you do anything else to install the required dependencies

**Comment by NodeGuy** [comment]
I'm so confused!  You want me to run `npm install` before I run `npm install sodium`?  How does that work?

I'm not even installing it myself directly; I'm trying to do `npm install telehash` which depends on `e3x`, which depends on `e3x-cs3a`, which depends on `sodium`:

```
npm install telehash

...

gyp: /node_modules/telehash/node_modules/e3x/node_modules/e3x-cs3a/node_modules/sodium/deps/libsodium.gyp not found (cwd: /node_modules/telehash/node_modules/e3x/node_modules/e3x-cs3a/node_modules/sodium) while loading dependencies of binding.gyp while trying to load binding.gyp
```

**Comment by paixaop** [comment]
The npm install telehash should run the npm install sodium

I will review

Pedro
