### ISSUE TITLE
Cannot install from npm

### ISSUE THREAD

**Issue by naoina** [paixaop/node-sodium#95]
I try to install sodium 1.2.0 from npm, but encountered the following errors.

```
> sodium@1.2.0 preinstall /home/naoina/work/src/github.com/tokyootakumode/com/node_modules/sodium
> node install.js --preinstall

Static libsodium was not found at /home/naoina/work/src/github.com/tokyootakumode/com/node_modules/sodium/deps/build/lib/libsodium so compiling libsodium from source.
autoreconf: Entering directory `.'
autoreconf: configure.ac: not using Gettext
autoreconf: running: aclocal --force -I m4
aclocal: warning: couldn't open directory 'm4': No such file or directory
autoreconf: configure.ac: tracing
autoreconf: configure.ac: creating directory build-aux
autoreconf: running: libtoolize --copy --force
libtoolize: putting auxiliary files in AC_CONFIG_AUX_DIR, 'build-aux'.
libtoolize: copying file 'build-aux/ltmain.sh'
libtoolize: putting macros in AC_CONFIG_MACRO_DIRS, 'm4'.
libtoolize: copying file 'm4/libtool.m4'
libtoolize: copying file 'm4/ltoptions.m4'
libtoolize: copying file 'm4/ltsugar.m4'
libtoolize: copying file 'm4/ltversion.m4'
libtoolize: copying file 'm4/lt~obsolete.m4'
autoreconf: running: /usr/bin/autoconf --force
autoreconf: configure.ac: not using Autoheader
autoreconf: running: automake --add-missing --copy --force-missing
configure.ac:117: installing 'build-aux/compile'
configure.ac:9: installing 'build-aux/config.guess'
configure.ac:9: installing 'build-aux/config.sub'
configure.ac:10: installing 'build-aux/install-sh'
configure.ac:10: installing 'build-aux/missing'
configure.ac:694: error: required file 'dist-build/Makefile.in' not found
configure.ac:694: error: required file 'test/default/Makefile.in' not found
Makefile.am:12: error: required directory ./dist-build does not exist
src/libsodium/Makefile.am:209: error: HAVE_LD_OUTPUT_DEF does not appear in AM_CONDITIONAL
src/libsodium/Makefile.am: installing 'build-aux/depcomp'
test/Makefile.am:1: error: required directory test/default does not exist
autoreconf: automake failed with exit status: 1
make: *** [Makefile:62: libsodium] エラー 1
/home/naoina/work/src/github.com/tokyootakumode/com/node_modules/sodium/install.js:288
            throw new Error(cmdLine + ' exited with code ' + code);
            ^

Error: make libsodium exited with code 2
    at ChildProcess.<anonymous> (/home/naoina/work/src/github.com/tokyootakumode/com/node_modules/sodium/install.js:288:19)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
npm WARN deprecated win-spawn@2.0.0: use [cross-spawn](https://github.com/IndigoUnited/node-cross-spawn) or [cross-spawn-async](https://github.com/IndigoUnited/node-cross-spawn-async) instead.
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm ERR! Linux 4.7.5-1-ARCH
npm ERR! argv "/home/naoina/.homesick/repos/dotfiles/home/.nvm/versions/v4.6.0/bin/node" "/home/naoina/.nvm/versions/v4.6.0/bin/npm" "i"
npm ERR! node v4.6.0
npm ERR! npm  v2.15.9
npm ERR! code ELIFECYCLE

npm ERR! sodium@1.2.0 preinstall: `node install.js --preinstall`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the sodium@1.2.0 preinstall script 'node install.js --preinstall'.
npm ERR! This is most likely a problem with the sodium package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node install.js --preinstall
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs sodium
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!
npm ERR!     npm owner ls sodium
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/naoina/work/src/github.com/tokyootakumode/com/npm-debug.log
```

sodium 1.2.0 on npm seems that there are no some directories.

**Comment by richchurcher** [comment]
You seem to be using Arch... is it possible you don't have recent versions of packages in `base-devel`?
```
pacman -S --needed base-devel
```

**Comment by naoina** [comment]
@richchurcher I'm using latest versions of `base-devel`. Also this issue has occurred on MacOS X v10.11 El Capitan as well. Please see the following log.

```
> sodium@1.2.0 preinstall /private/tmp/node_modules/sodium
> node install.js --preinstall

Static libsodium was not found at /private/tmp/node_modules/sodium/deps/build/lib/libsodium so compiling libsodium from source.
autoreconf: Entering directory `.'
autoreconf: configure.ac: not using Gettext
autoreconf: running: aclocal --force -I m4
aclocal: warning: couldn't open directory 'm4': No such file or directory
autoreconf: configure.ac: tracing
autoreconf: configure.ac: creating directory build-aux
autoreconf: running: glibtoolize --copy --force
glibtoolize: putting auxiliary files in AC_CONFIG_AUX_DIR, 'build-aux'.
glibtoolize: copying file 'build-aux/ltmain.sh'
glibtoolize: putting macros in AC_CONFIG_MACRO_DIRS, 'm4'.
glibtoolize: copying file 'm4/libtool.m4'
glibtoolize: copying file 'm4/ltoptions.m4'
glibtoolize: copying file 'm4/ltsugar.m4'
glibtoolize: copying file 'm4/ltversion.m4'
glibtoolize: copying file 'm4/lt~obsolete.m4'
autoreconf: running: /usr/local/Cellar/autoconf/2.69/bin/autoconf --force
configure.ac:94: error: possibly undefined macro: AC_DEFINE
      If this token and others are legitimate, please use m4_pattern_allow.
      See the Autoconf documentation.
configure.ac:172: error: possibly undefined macro: AC_CHECK_DEFINE
autoreconf: /usr/local/Cellar/autoconf/2.69/bin/autoconf failed with exit status: 1
make: *** [libsodium] Error 1
/private/tmp/node_modules/sodium/install.js:288
            throw new Error(cmdLine + ' exited with code ' + code);
            ^

Error: make libsodium exited with code 2
    at ChildProcess.<anonymous> (/private/tmp/node_modules/sodium/install.js:288:19)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
npm ERR! Darwin 15.6.0
npm ERR! argv "/Users/ms76/.nodebrew/node/v4.6.0/bin/node" "/Users/ms76/.nodebrew/current/bin/npm" "install" "sodium@latest"
npm ERR! node v4.6.0
npm ERR! npm  v2.15.9
npm ERR! code ELIFECYCLE

npm ERR! sodium@1.2.0 preinstall: `node install.js --preinstall`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the sodium@1.2.0 preinstall script 'node install.js --preinstall'.
npm ERR! This is most likely a problem with the sodium package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node install.js --preinstall
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs sodium
npm ERR! Or if that isn't available, you can get their info via:
npm ERR! 
npm ERR!     npm owner ls sodium
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /private/tmp/npm-debug.log
```

**Comment by paixaop** [comment]
Fixed the .gitignore to include the libsodium m4 directory, can you test it now?
Updated the npmjs module up to 1.2.1.

**Comment by naoina** [comment]
@paixaop I just tested now, but has not been fixed yet.

```
> sodium@1.2.1 preinstall /home/naoina/work/src/github.com/tokyootakumode/com/node_modules/sodium
> node install.js --preinstall

Static libsodium was not found at /home/naoina/work/src/github.com/tokyootakumode/com/node_modules/sodium/deps/build/lib/libsodium so compiling libsodium from source.
autoreconf: Entering directory `.'
autoreconf: configure.ac: not using Gettext
autoreconf: running: aclocal --force -I m4
autoreconf: configure.ac: tracing
autoreconf: configure.ac: creating directory build-aux
autoreconf: running: libtoolize --copy --force
libtoolize: putting auxiliary files in AC_CONFIG_AUX_DIR, 'build-aux'.
libtoolize: copying file 'build-aux/ltmain.sh'
libtoolize: putting macros in AC_CONFIG_MACRO_DIRS, 'm4'.
libtoolize: copying file 'm4/libtool.m4'
libtoolize: copying file 'm4/ltoptions.m4'
libtoolize: copying file 'm4/ltsugar.m4'
libtoolize: copying file 'm4/ltversion.m4'
libtoolize: copying file 'm4/lt~obsolete.m4'
autoreconf: running: /usr/bin/autoconf --force
autoreconf: configure.ac: not using Autoheader
autoreconf: running: automake --add-missing --copy --force-missing
configure.ac:117: installing 'build-aux/compile'
configure.ac:9: installing 'build-aux/config.guess'
configure.ac:9: installing 'build-aux/config.sub'
configure.ac:10: installing 'build-aux/install-sh'
configure.ac:10: installing 'build-aux/missing'
configure.ac:694: error: required file 'dist-build/Makefile.in' not found
configure.ac:694: error: required file 'test/default/Makefile.in' not found
Makefile.am:12: error: required directory ./dist-build does not exist
src/libsodium/Makefile.am: installing 'build-aux/depcomp'
test/Makefile.am:1: error: required directory test/default does not exist
autoreconf: automake failed with exit status: 1
make: *** [Makefile:62: libsodium] エラー 1
/home/naoina/work/src/github.com/tokyootakumode/com/node_modules/sodium/install.js:288
            throw new Error(cmdLine + ' exited with code ' + code);
            ^

Error: make libsodium exited with code 2
    at ChildProcess.<anonymous> (/home/naoina/work/src/github.com/tokyootakumode/com/node_modules/sodium/install.js:288:19)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
npm WARN deprecated win-spawn@2.0.0: use [cross-spawn](https://github.com/IndigoUnited/node-cross-spawn) or [cross-spawn-async](https://github.com/IndigoUnited/node-cross-spawn-async) instead.
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm ERR! Linux 4.7.5-1-ARCH
npm ERR! argv "/home/naoina/.homesick/repos/dotfiles/home/.nvm/versions/v4.6.0/bin/node" "/home/naoina/.nvm/versions/v4.6.0/bin/npm" "i"
npm ERR! node v4.6.0
npm ERR! npm  v2.15.9
npm ERR! code ELIFECYCLE

npm ERR! sodium@1.2.1 preinstall: `node install.js --preinstall`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the sodium@1.2.1 preinstall script 'node install.js --preinstall'.
npm ERR! This is most likely a problem with the sodium package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node install.js --preinstall
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs sodium
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!
npm ERR!     npm owner ls sodium
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/naoina/work/src/github.com/tokyootakumode/com/npm-debug.log
```

**Comment by paixaop** [comment]
it's working for me now, can you check again. Was too restrictive on the .gitignore

**Comment by naoina** [comment]
@paixaop It works on my environment now! Thank you!

**Comment by paixaop** [comment]
Great. thanks for the feedback
