### ISSUE TITLE
Installation failed on OS X 10.11

### ISSUE THREAD

**Issue by luzianscherrer** [paixaop/node-sodium#96]
```
host% sw_vers 
ProductName:	Mac OS X
ProductVersion:	10.11.6
BuildVersion:	15G1004
host% uname -a
Darwin alderaan.local 15.6.0 Darwin Kernel Version 15.6.0: Mon Aug 29 20:21:34 PDT 2016; root:xnu-3248.60.11~1/RELEASE_X86_64 x86_64
host% npm install sodium
-
> sodium@1.2.0 preinstall /usr/local/myproject/software/node_modules/sodium
> node install.js --preinstall

Static libsodium was not found at /usr/local/myproject/software/node_modules/sodium/deps/build/lib/libsodium so compiling libsodium from source.
autoreconf: Entering directory `.'
autoreconf: configure.ac: not using Gettext
autoreconf: running: aclocal --force -I m4
aclocal: warning: couldn't open directory 'm4': No such file or directory
autoreconf: configure.ac: tracing
autoreconf: configure.ac: creating directory build-aux
autoreconf: running: libtoolize --copy --force
libtoolize: putting auxiliary files in AC_CONFIG_AUX_DIR, 'build-aux'.
libtoolize: copying file 'build-aux/ltmain.sh'
libtoolize: putting macros in AC_CONFIG_MACRO_DIRS, 'm4'.
libtoolize: copying file 'm4/libtool.m4'
libtoolize: copying file 'm4/ltoptions.m4'
libtoolize: copying file 'm4/ltsugar.m4'
libtoolize: copying file 'm4/ltversion.m4'
libtoolize: copying file 'm4/lt~obsolete.m4'
autoreconf: running: /usr/local/myproject/software/bin/autoconf --force
configure.ac:94: error: possibly undefined macro: AC_DEFINE
      If this token and others are legitimate, please use m4_pattern_allow.
      See the Autoconf documentation.
configure.ac:172: error: possibly undefined macro: AC_CHECK_DEFINE
autoreconf: /usr/local/myproject/software/bin/autoconf failed with exit status: 1
make: *** [libsodium] Error 1
/usr/local/myproject/software/node_modules/sodium/install.js:288
            throw new Error(cmdLine + ' exited with code ' + code);
            ^

Error: make libsodium exited with code 2
    at ChildProcess.<anonymous> (/usr/local/myproject/software/node_modules/sodium/install.js:288:19)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
npm ERR! Darwin 15.6.0
npm ERR! argv "/usr/local/myproject/software/bin/node" "/usr/local/myproject/software/bin/npm" "install" "sodium"
npm ERR! node v4.6.0
npm ERR! npm  v2.15.9
npm ERR! code ELIFECYCLE

npm ERR! sodium@1.2.0 preinstall: `node install.js --preinstall`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the sodium@1.2.0 preinstall script 'node install.js --preinstall'.
npm ERR! This is most likely a problem with the sodium package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node install.js --preinstall
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs sodium
npm ERR! Or if that isn't available, you can get their info via:
npm ERR! 
npm ERR!     npm owner ls sodium
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /usr/local/myproject/software/npm-debug.log
```

**Comment by richchurcher** [comment]
I can't reproduce this on OS X 10.11.5. Since it's an autotools-related error, would it be worth checking:
```
autoconf --version
automake --version
libtool -V
```
I have it working here with GNU Autoconf 2.69 and GNU Automake 1.15. I installed those using:
```
brew install libtool autoconf automake
```

**Comment by paixaop** [comment]
check #95

**Comment by sarahscheffler** [comment]
BTW, it may be worth putting the libtool/autoconf/automake dependencies up on the main README for OSX.  I had this same problem in April 2017 installing from a new-ish computer that didn't actually have any of them, and I got the same error as above.  (For what it's worth, I installed node and npm through Homebrew; not sure if it matters.)
